### ISSUE TITLE
Kraken - Finished

### ISSUE THREAD

**Issue by askaalyy** [askaalyy/kraken-good-accessibility#1]
Hi @thatkidmadrid

completed activity.

**Comment by thatkidmadrid** [comment]
There are a few items that need to be revised before I can give you the grade
- be careful with the way you're structuring the page and using the article tag; you're on the right track but you can take the first footer you have as well as the div with the `role="main"` and put it in the same article as the header.
- `<article>` tags specify content that should make sense on their own ([w2 docs on articles](https://www.w3schools.com/tags/tag_article.asp)). Although you can argue that the header, main, and footer could make sense on their own for some edge cases, what makes the most sense in my opinion is to have them together in one article.
- There is another html tag that exists that's better suited for the image inside the text. please refer to [the html cheat sheet](https://learn-the-web.algonquindesign.ca/topics/html-semantics-cheat-sheet/)
- Be careful with spelling - especially in descriptions.
- The description you used is not very descriptive.
  - you just had `image of karken`
but this could be made even better with `a black and white illustration of kraken sinking a ship` just something small like that provides a lot more context. There's no ambiguity of if it's a photo, a 3d-render, etc.
  - That being said for this application I don't need to be overly detailed like `a black and white charcoal illustration of the 8-armed sea creature, the kraken, with its arms surrounding a half-submerged ship with a ship and seagulls in the background` Use your judgement, put yourself in the listener's shoes, and think of a description that would help you understand the image. In some applications (like a design portfolio 😉 ) a very detailed description may be helpful, but then that introduces other accessibility options like `aria-details`
  - The styling of your footer with the nav is a bit off and this could be from how you structured the page, but I also noticed you added some css. For this exercise the only css that you needed to add was for the hover/focus states for the navigation
  - The focus state styling is not what I expect to see from the screenshot. Please refer to [the lesson section about focus styles](https://learn-the-web.algonquindesign.ca/topics/accessibility-for-design/#keyboard-focus-styles)
